# coding: utf-8

"""
    Processing Project

    This is the api for the processing project backend.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.param_set import ParamSet  # noqa: E501
from swagger_client.rest import ApiException


class TestParamSet(unittest.TestCase):
    """ParamSet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParamSet(self):
        """Test ParamSet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.param_set.ParamSet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
