# coding: utf-8

"""
    Processing Project

    This is the api for the processing project backend.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.layer import Layer  # noqa: E501
from swagger_client.rest import ApiException


class TestLayer(unittest.TestCase):
    """Layer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLayer(self):
        """Test Layer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.layer.Layer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
