# coding: utf-8

"""
    Processing Project

    This is the api for the processing project backend.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.model_configurations_api import ModelConfigurationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestModelConfigurationsApi(unittest.TestCase):
    """ModelConfigurationsApi unit test stubs"""

    def setUp(self):
        self.api = api.model_configurations_api.ModelConfigurationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_configuration(self):
        """Test case for create_configuration

        Creates a model configuration.  # noqa: E501
        """
        pass

    def test_download_configuration(self):
        """Test case for download_configuration

        Retreive signed url to download binary  # noqa: E501
        """
        pass

    def test_get_configuration(self):
        """Test case for get_configuration

        Returns a model configuration  # noqa: E501
        """
        pass

    def test_get_configurations(self):
        """Test case for get_configurations

        Returns all of a users model configurations.  # noqa: E501
        """
        pass

    def test_launch_configuration(self):
        """Test case for launch_configuration

        Launch a configuration to one of the workers to be processed.  # noqa: E501
        """
        pass

    def test_update_configuration(self):
        """Test case for update_configuration

        Update and replace a model configuration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
